name: Teste de Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_code_linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.13

    - name: Instalar uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Sincronizar venv
      run: uv sync --dev

    - name: Ativar venv
      run: source .venv/bin/activate

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_SECRET_KEY: "SECRET_KEY"
        envkey_DEBUG: 1

    - name: Executar Linter
      run: task lint